## numpy array and  basics 
learn about numpy 

In [ ]:
import numpy as np

### creating array from list 

In [ ]:
array_1d=np.array([1,2,3,4,5])
print("1D array:",array_1d)
array_2d=np.array([[1,2],[3,4],[5,6]])
print("2D-array:",array_2d)

1D array: [1 2 3 4 5]
2D-array: [[1 2]
 [3 4]
 [5 6]]


### list vs numpy array 

In [ ]:
py_list =[1,2,3]
print("python list multipication", py_list*2)

np_array=np.array([1,2,3]) #elment wise multipication 
print("python array multipication", np_array*2)
import time
start=time.time()
py_list=[i*2 for i in range(1000000)]
print("\n  list operation time:",time.time()-start)

start=time.time()
np_array=np.arange(1000000)*2
print("\n  numpy operation time:",time.time()-start)

python list multipication [1, 2, 3, 1, 2, 3]
python array multipication [2 4 6]

  list operation time: 0.047269582748413086

  numpy operation time: 0.0010080337524414062


### creating array from scratch

In [ ]:
zeros=np.zeros((3,4))
print("zeroes array\n",zeros)

ones =np.ones((3,3))
print("ones array\n",ones)

full=np.full((2,2),7)
print("full array\n",full)

random=np.random.random((2,3))
print("random array\n",random)

sequence= np.arange(0,10,2)
print("sequence array\n",sequence)

zeroes array
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
full array
 [[7 7]
 [7 7]]
random array
 [[0.55088889 0.71277441 0.1463955 ]
 [0.26622595 0.35666946 0.09494663]]
sequence array
 [0 2 4 6 8]


### vector , matrix and tensor

In [ ]:
vector = np.array([1,2,3])
print("vector :",vector)

matrix= np.array([[1,2],[3,4],[5,6]])
print("matrix :",matrix)

tensor =np.array([[[1,2],[3,4]]
                  ,[[5,6],[7,8]]
                  ])
print("tensor :",tensor)

vector : [1 2 3]
matrix : [[1 2]
 [3 4]
 [5 6]]
tensor : [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### array propeties

In [ ]:
arr= np.array([[1,2,3],
               [4,5,6.9]])
print("shape",arr.shape)
print("dimension",arr.ndim)
print("size",arr.size)
print("Dtype",arr.dtype)

shape (2, 3)
dimension 2
size 6
Dtype float64


### array reshaping

In [ ]:
arr =np.arange(12)
print("original array",arr)
reshaped =arr.reshape((3,4))
print("\n reshaped array",reshaped)

flattened= reshaped.flatten()
print("\n flattened array",flattened)
# ravel {returns view, insted of copy}
raveled =reshaped.ravel()
print("\n raveled array",raveled)

# transpose
transpose= reshaped.T
print("transpose:",transpose)




original array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 reshaped array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 flattened array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]
transpose: [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
