## numpy array operation 

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("basic slicing",arr[2:7])
print("with step slicing",arr[0:8:2])
print("negative indexing",arr[-3])

basic slicing [3 4 5 6 7]
with step slicing [1 3 5 7]
negative indexing 8


In [ ]:
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print("specific element in matrix",arr_2d[1,0])
print("Entire row in matrix :",arr_2d[0])
print("Entire row in matrix :",arr_2d[:,0])

specific element in matrix 4
Entire row in matrix : [1 2 3]
Entire row in matrix : [1 4 7]


## sorting

In [ ]:
unsorted =np.array([4,3,2,6,8,5])
print("sorted array",np.sort(unsorted))
arr_2d_unsorted=np.array([[3,1],[2,3],[1,2]])
print("sorted 2d array by column",np.sort(arr_2d_unsorted, axis=0))
print("sorted 2d array by row",np.sort(arr_2d_unsorted, axis=1))


sorted array [2 3 4 5 6 8]
sorted 2d array by column [[1 1]
 [2 2]
 [3 3]]
sorted 2d array by row [[1 3]
 [2 3]
 [1 2]]


## filtering

In [ ]:
numbers= np.array([1,2,3,4,5,6,7,8,9,10])
even_number= numbers[numbers % 2==0]
print("Even",even_number)
odd_number =numbers[numbers%2!=0]
print("Odd",odd_number)

Even [ 2  4  6  8 10]
Odd [1 3 5 7 9]


filter with mask

In [ ]:
mask = numbers > 5
print("numbers greater than 5",numbers[mask])

numbers greater than 5 [ 6  7  8  9 10]


## fancy indexing vs np.where()

In [ ]:
indices =[0,2,4]
print(numbers[indices])
where_result= np.where(numbers>5)
print("np where",numbers[where_result])

[1 3 5]
np where [ 6  7  8  9 10]


In [ ]:
condition_array =np.where(numbers>5,numbers*4,numbers)#(conditon ,true happen,false happen)
print(condition_array)

[ 1  2  3  4  5 24 28 32 36 40]


### adding and removing data 

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
combing= np.concatenate((arr1,arr2))
print(combing)

[1 2 3 4 5 6]


### array compatibiltiy

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])
print("compatitivilty shapes ",a.shape == b.shape)

compatitivilty shapes  True


In [ ]:
original=np.array([[1,2],[3,4]])
new_row =np.array([[5,6]])
with_new_row =np.vstack((original,new_row))
print(original)
print(with_new_row)

new_col = np.array([[7],[8]])
with_new_col=np.hstack((original,new_col))
print(with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


In [ ]:
arr= np.array([1,2,3,4,5])
delete=np.delete(arr,2)
print("array after deletion:",delete)

array after deletion: [1 2 4 5]
